-- ============================================================================
-- account 库 · 初始化（PostgreSQL 17）
-- ============================================================================

CREATE TABLE IF NOT EXISTS account_user (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email      VARCHAR(191) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    nickname   VARCHAR(64)  NOT NULL DEFAULT '',
    gender     SMALLINT     NOT NULL DEFAULT 0,
    avatar_url VARCHAR(512) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_account_user PRIMARY KEY (id),
    -- 唯一约束同时承担「邮箱不可重复」的并发兜底职责：
    -- 即使两个注册请求同时通过了前置校验，也只有一个能写入成功。
    CONSTRAINT uk_account_user_email UNIQUE (email)
);

COMMENT ON TABLE  account_user            IS '账号表';
COMMENT ON COLUMN account_user.id         IS '用户 ID';
COMMENT ON COLUMN account_user.email      IS '登录邮箱，全局唯一';
COMMENT ON COLUMN account_user.password   IS 'bcrypt 哈希，禁止存明文';
COMMENT ON COLUMN account_user.nickname   IS '昵称';
COMMENT ON COLUMN account_user.gender     IS '0 未知 1 男 2 女';
COMMENT ON COLUMN account_user.avatar_url IS '头像地址';
COMMENT ON COLUMN account_user.created_at IS '创建时间';
-- 注意：PostgreSQL 不支持 MySQL 的 ON UPDATE CURRENT_TIMESTAMP，
-- updated_at 由应用侧（GORM 的 autoUpdateTime）在每次写入时维护。
COMMENT ON COLUMN account_user.updated_at IS '更新时间，由应用侧维护';
