-- ============================================================================
-- account 库 · 在线令牌表（PostgreSQL 17）
--
-- 用途：持久化「已签发且仍然有效」的访问令牌，支撑两件事：
--   1. 多设备在线上限：超限时踢出最早的设备，并在此表把它的令牌置为已吊销；
--   2. TOKEN_MODE=db 的严格校验：JWT 自校验通过后，还要求此表存在且未被吊销。
--
-- 设计要点：
--   - jti 是令牌的唯一标识（JWT 的 jti claim），而不是整串 token 本身。
--     存整串会让每行长达数百字节且包含签名，既浪费空间又可能把凭证
--     泄露给有库只读权限的人；存 jti 则无此风险，且查询更快。
--   - device_id 由客户端上报，用于表达「同一台设备」。
--     同一设备重新登录时复用同一行（按 uk_account_token_device 冲突更新），
--     避免同一台设备反复登录把在线位占满。
--   - revoked_at 用「是否为空」而不是布尔列表达吊销：
--     空值天然携带「何时被吊销」这一信息，便于安全审计。
-- ============================================================================

CREATE TABLE IF NOT EXISTS account_token (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    -- jti 是 JWT 的唯一标识，长度为 36（UUID 文本形式）
    jti           VARCHAR(64)  NOT NULL,
    -- device_id 由客户端生成并持久化；为空时回落到 jti（见应用侧说明）
    device_id     VARCHAR(128) NOT NULL DEFAULT '',
    platform      VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    -- 令牌自身的过期时间，与 JWT 的 exp 一致，便于按时间清理历史行
    expire_at     TIMESTAMPTZ  NOT NULL,
    -- 为空表示仍然有效；非空表示已被吊销（登出、被踢出、改密）
    revoked_at    TIMESTAMPTZ,
    -- 吊销原因，便于区分「用户主动登出」与「被新设备挤下线」
    revoked_by    VARCHAR(32)  NOT NULL DEFAULT '',
    -- 最后一次看到该令牌活跃的时间，用于运维观察
    last_seen_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_account_token PRIMARY KEY (id),
    -- jti 全局唯一：同一个令牌不可能对应两行，也是并发签发时的兜底
    CONSTRAINT uk_account_token_jti UNIQUE (jti)
);

-- 按 (user_id, device_id) 建**普通**索引，用于「按设备反查令牌」（踢人路径）。
--
-- 刻意不是唯一索引，原因在 PostgreSQL 的 upsert 规则：
--   部分唯一索引 (...) WHERE device_id <> '' 无法作为 ON CONFLICT 的仲裁索引，
--   除非语句里重复同样的 WHERE 谓词（否则报 SQLSTATE 42P10）。而 GORM 的
--   clause.OnConflict 无法生成该谓词。若改成不带谓词的全局唯一索引，
--   客户端未上报 device_id（空串）时每次登录都会撞同一行、覆盖 jti，
--   导致库与 Redis 有序集合错位。
--
-- 因此「同一设备只保留一行」改由应用层保证：
-- account_token 的写入路径会先按 device_id 删除历史行（CleanupDevice），
-- 再插入新令牌。这里只需一个普通索引来加速该反查与删除。
CREATE INDEX IF NOT EXISTS idx_account_token_device
    ON account_token (user_id, device_id);

-- 查询某用户的全部有效令牌（踢人时需要、审计时也需要）
CREATE INDEX IF NOT EXISTS idx_account_token_user
    ON account_token (user_id, revoked_at);

-- 按过期时间清理历史行（可由定时任务使用）
CREATE INDEX IF NOT EXISTS idx_account_token_expire
    ON account_token (expire_at);

COMMENT ON TABLE  account_token              IS '在线访问令牌表：记录已签发且可被吊销的令牌';
COMMENT ON COLUMN account_token.id           IS '自增主键';
COMMENT ON COLUMN account_token.user_id      IS '所属用户 ID';
COMMENT ON COLUMN account_token.jti          IS 'JWT 唯一标识（jti claim），不存令牌原文';
COMMENT ON COLUMN account_token.device_id    IS '客户端设备标识，同设备重新登录复用同一行';
COMMENT ON COLUMN account_token.platform     IS '客户端平台标识，如 web / ios / android';
COMMENT ON COLUMN account_token.expire_at    IS '令牌自身过期时间，与 JWT 的 exp 一致';
COMMENT ON COLUMN account_token.revoked_at   IS '吊销时间，为空表示仍然有效';
COMMENT ON COLUMN account_token.revoked_by   IS '吊销原因：logout 登出 / evicted 被顶下线 / password_reset 改密';
COMMENT ON COLUMN account_token.last_seen_at  IS '最后一次校验通过的时间';
COMMENT ON COLUMN account_token.created_at   IS '创建时间';
COMMENT ON COLUMN account_token.updated_at   IS '更新时间，由应用侧维护';
