-- ============================================================================
-- chat 库 · 初始化（PostgreSQL 17）
--
-- 设计要点：
--   1. 会话（conversation）统一承载单聊与群聊，避免两套模型；
--   2. 消息顺序性由会话内的 seq 保证，而非依赖全局自增主键——
--      后者在分表后会失效，seq 则可以随会话一起分片；
--   3. 幂等由 client_msg_id 唯一约束兜底，重试不会产生重复消息；
--   4. message_outbox 是本地消息表，保证「落库」与「投递」的原子性。
-- ============================================================================

-- ── 会话 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversation (
    id         BIGINT       NOT NULL,
    type       SMALLINT     NOT NULL,
    biz_key    VARCHAR(191) NOT NULL,
    name       VARCHAR(191) NOT NULL DEFAULT '',
    avatar_url VARCHAR(512) NOT NULL DEFAULT '',
    status     SMALLINT     NOT NULL DEFAULT 1,
    owner_id   BIGINT       NOT NULL DEFAULT 0,
    max_seq    BIGINT       NOT NULL DEFAULT 0,
    extra      JSONB,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_conversation PRIMARY KEY (id),
    -- 单聊的 biz_key 为 "minUid_maxUid"，群聊为雪花串；
    -- 该唯一约束保证同一对用户只会存在一个单聊会话。
    CONSTRAINT uk_conversation_type_bizkey UNIQUE (type, biz_key)
);
CREATE INDEX IF NOT EXISTS idx_conversation_owner ON conversation (owner_id);

COMMENT ON TABLE  conversation           IS '会话表，单聊与群聊统一建模';
COMMENT ON COLUMN conversation.id        IS '会话 ID（雪花）';
COMMENT ON COLUMN conversation.type      IS '1 单聊 2 群聊';
COMMENT ON COLUMN conversation.biz_key   IS '业务去重键：单聊为 minUid_maxUid，群聊为雪花串';
COMMENT ON COLUMN conversation.status    IS '1 正常 2 待确认 3 拉黑';
COMMENT ON COLUMN conversation.owner_id  IS '群主用户 ID，单聊为 0';
COMMENT ON COLUMN conversation.max_seq   IS '会话内最新序号，用于快速对齐';

-- ── 会话成员 ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversation_member (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    alias_name      VARCHAR(191) NOT NULL DEFAULT '',
    role            SMALLINT    NOT NULL DEFAULT 0,
    last_read_seq   BIGINT      NOT NULL DEFAULT 0,
    mute            SMALLINT    NOT NULL DEFAULT 0,
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_conversation_member PRIMARY KEY (id),
    -- 幂等加入：重复拉人不会产生重复成员
    CONSTRAINT uk_conversation_member UNIQUE (conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conversation_member_user ON conversation_member (user_id, conversation_id);

COMMENT ON TABLE  conversation_member                 IS '会话成员表';
COMMENT ON COLUMN conversation_member.alias_name      IS '用户对该会话的备注名';
COMMENT ON COLUMN conversation_member.role            IS '0 成员 1 管理员 2 群主';
COMMENT ON COLUMN conversation_member.last_read_seq   IS '已读位点，用于计算未读数';
COMMENT ON COLUMN conversation_member.mute            IS '是否免打扰';

-- ── 消息 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS message (
    id              BIGINT       NOT NULL,
    conversation_id BIGINT       NOT NULL,
    seq             BIGINT       NOT NULL,
    sender_id       BIGINT       NOT NULL,
    type            SMALLINT     NOT NULL DEFAULT 1,
    content         TEXT,
    extra           JSONB,
    client_msg_id   VARCHAR(64)  NOT NULL,
    status          SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_message PRIMARY KEY (id),
    -- 顺序权威：同一会话内 seq 唯一且单调递增
    CONSTRAINT uk_message_conv_seq UNIQUE (conversation_id, seq),
    -- 幂等权威：同一发送者用同一 client_msg_id 重试只会落地一条
    CONSTRAINT uk_message_conv_clientmsg UNIQUE (conversation_id, sender_id, client_msg_id)
);
CREATE INDEX IF NOT EXISTS idx_message_conv_created ON message (conversation_id, created_at);

COMMENT ON TABLE  message                IS '消息表';
COMMENT ON COLUMN message.id             IS '消息 ID（雪花）';
COMMENT ON COLUMN message.seq            IS '会话内序号，顺序权威';
COMMENT ON COLUMN message.type           IS '1 文本 2 图片 3 视频 4 音频 5 系统';
COMMENT ON COLUMN message.extra          IS '扩展信息（富媒体元数据等），JSON 字符串';
COMMENT ON COLUMN message.client_msg_id  IS '客户端幂等键';
COMMENT ON COLUMN message.status         IS '1 正常 2 撤回 3 删除';

-- ── 好友关系 ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS friend_relation (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL,
    friend_id  BIGINT       NOT NULL,
    remark     VARCHAR(191) NOT NULL DEFAULT '',
    status     SMALLINT     NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_friend_relation PRIMARY KEY (id),
    CONSTRAINT uk_friend_relation UNIQUE (user_id, friend_id)
);
CREATE INDEX IF NOT EXISTS idx_friend_relation_friend ON friend_relation (friend_id);

COMMENT ON TABLE  friend_relation         IS '好友关系表，双向各存一行';
COMMENT ON COLUMN friend_relation.remark  IS '好友备注名';
COMMENT ON COLUMN friend_relation.status  IS '1 正常 2 拉黑';

-- ── 好友申请 ────────────────────────────────────────────────────────────────
-- 独立成表而非复用消息表：申请是有状态的业务实体，需要按状态检索与统计。
CREATE TABLE IF NOT EXISTS friend_request (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    from_uid   BIGINT       NOT NULL,
    to_uid     BIGINT       NOT NULL,
    apply_msg  VARCHAR(255) NOT NULL DEFAULT '',
    status     SMALLINT     NOT NULL DEFAULT 0,
    expire_at  TIMESTAMPTZ  NOT NULL,
    handled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_friend_request PRIMARY KEY (id),
    CONSTRAINT uk_friend_request UNIQUE (from_uid, to_uid, status)
);
CREATE INDEX IF NOT EXISTS idx_friend_request_to ON friend_request (to_uid, status);

COMMENT ON TABLE  friend_request            IS '好友申请表';
COMMENT ON COLUMN friend_request.status     IS '0 待处理 1 已同意 2 已拒绝 3 已过期';
COMMENT ON COLUMN friend_request.expire_at  IS '过期时间，避免僵尸申请长期占用唯一约束';

-- ── 本地消息表（Outbox） ────────────────────────────────────────────────────
-- 与业务写入放在同一事务中，再由后台协程投递到消息队列，
-- 从而保证「消息落库」与「消息投递」的原子性，避免写库成功但投递失败。
CREATE TABLE IF NOT EXISTS message_outbox (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    event_id      VARCHAR(64)  NOT NULL,
    topic         VARCHAR(64)  NOT NULL,
    partition_key VARCHAR(64)  NOT NULL,
    payload       BYTEA        NOT NULL,
    status        SMALLINT     NOT NULL DEFAULT 0,
    retry_count   INT          NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_message_outbox PRIMARY KEY (id),
    CONSTRAINT uk_message_outbox_event UNIQUE (event_id)
);
CREATE INDEX IF NOT EXISTS idx_message_outbox_pending ON message_outbox (status, next_retry_at);

COMMENT ON TABLE  message_outbox               IS '本地消息表，保证落库与投递的原子性';
COMMENT ON COLUMN message_outbox.partition_key IS '分区键，取会话 ID 以保证同会话消息进入同一分区从而有序';
COMMENT ON COLUMN message_outbox.status        IS '0 待投递 1 已投递 2 失败';
