// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jesse-467/im/Account/internal/biz"
	"github.com/Jesse-467/im/Account/internal/conf"
	"github.com/Jesse-467/im/Account/internal/data"
	"github.com/Jesse-467/im/Account/internal/server"
	"github.com/Jesse-467/im/Account/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"time"
)

// Injectors from wire.go:

// initApp 的装配实现由 Wire 在编译期生成到 wire_gen.go，运行时零反射开销。
//
// 依赖关系完全由各层的 ProviderSet 声明，新增组件只需改动对应的 ProviderSet，
// 无需手工维护初始化顺序。
func initApp(cfg *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	accountService := service.NewAccountService(userUseCase, cfg, logger)
	postgresChecker := data.NewPostgresChecker(dataData)
	redisChecker := data.NewRedisChecker(dataData)
	v := data.NewHealthCheckers(postgresChecker, redisChecker)
	httpServer := server.NewHTTPServer(cfg, logger, accountService, v)
	grpcServer := server.NewGRPCServer(cfg, logger, accountService)
	app := newApp(cfg, logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// newApp 组装 Kratos 应用，统一管理 HTTP 与 gRPC 两个传输层的生命周期。
//
// 这正是 Gin 实现 transport.Server 的价值：Gin 与 gRPC 由同一个 kratos.App
// 统一启停，因此优雅退出、信号处理、启动顺序都无需自己实现。
func newApp(
	cfg *conf.Config,
	logger log.Logger,
	hs *server.HTTPServer,
	gs *grpc.Server,
) *kratos.App {
	return kratos.New(kratos.Name(cfg.ServiceName), kratos.Version(Version), kratos.Logger(logger), kratos.StopTimeout(15*time.Second), kratos.Server(hs, gs))
}
